### PR TITLE
updated name of appimageupdatertool

### PR DESCRIPTION
**Pull request by indika-dev**
The name of appimageupdatertool was changed to AppImageUpdate-*.AppImage. I changed the script accordingly on line 7. 
The other changes were made by shellfmt.

makefile lost it's executable flag, because it shoudln't be executable.

Kind regards,
Stefan

### CODE REVIEW

**Comment by mttbernardini** [comment]
Thanks for the fix!

I wasn't aware of the change since I'm not using this tool anymore, I'll fix this on the `python` branch as well.

PS: is there any particular reason on why `makefile` shouldn't be executable? I usually see makefiles starting with a shebang (which only makes sense if the makefile is an executable script), I thought calling them through `make` was just a matter of convention (like `python`).

Best regards

**Comment by mttbernardini** [comment]
On a second note (sorry for merging this too quickly),

I just noticed on the [AppImageUpdate](https://github.com/AppImage/AppImageUpdate/releases) repo releases that both `AppImageUpdate-*.AppImage` and `appimageupdatetool-*.AppImage` are provided as usual. As far as I can rembember, the former is a GUI tool, the second is a CLI tool which is the one needed for this program.

Are you having issues with `appimageupdatetool-*.AppImage`? Or is there any deprecation notice that I'm unaware of for which the former is preferred?

Again, sorry for the merge-revert...

**Comment by indika-dev** [comment]
I tested AppImageUpdate together with your tool and the script failed to find appimageupdatetool:
I downloaded AppImageUpdate from AppImage Hub and I was unable to find appimageupdatetool in the GitHub Repo from AppImageUpdate. I took a look in your script and the script is looking for a file. Then I changed the filename and everything went fine. I tested it with successfully updating nvim.appimage . Your last commit was 10 months ago, so I thought the name was changed meanwhile and I prepared the pull request.
If I overlooked something, sorry for the inconvinience.

Am 3. Januar 2022 17:05:08 MEZ schrieb Matteo Bernardini ***@***.***>:

**Comment by indika-dev** [comment]
I don't know, why I overlooked appimageupdatetool in the releases... Sorry for the inconvinience! 
merge-revert is perfectly OK, since I should search better. ;)

Am 3. Januar 2022 17:05:08 MEZ schrieb Matteo Bernardini ***@***.***>:

**Comment by mttbernardini** [comment]
No problem at all!
If anything, I think it should be better to auto-download the updater or at least provide some more meaningful message rather than "appimageupdatetool not found". Thank you for sharing your experience and I hope this little tool is being helpful to you, feel free to open any other issue/PR if needed ;)

Best regards

**Pull request merged**
